name: Deploy Vite React App to GitHub Pages

on:
  push:
    branches:
      - main   # redeploy every time you push to main
  workflow_dispatch:   # also allow manual deploys from GitHub UI

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      # Ensure the CV file is included in deployment
      - name: Verify CV file
        run: ls -lh public/ | grep "ayush_chaubey_cv_compressed.pdf"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
